FZJ-INM1-BDA/siibra-api

- .coveragerc
- .github/workflows/github-actions.yml
- .gitignore
- app/app.py
- app/diskcache.py
- app/parcellation_api.py
- app/request_utils.py
- app/requirements.txt
- app/siibra_api.py
- app/space_api.py
- test/test_atlas_api.py
- test/test_parcellation_api.py
- test/test_siibra_api.py
- test/test_space_api.py
dependent on https://github.com/FZJ-INM1-BDA/siibra-python/pull/39 do not merge until above is merged
> feat: arbitrary kg regional features

- app/parcellation_api.py
- app/request_utils.py
- test/test_request_utils.py
bugfix: update siibra-python nifti vol src
chore: added test to catch siibra python change
> bugfix: update to regional continuous map (prob map) in siibra-python

- Dockerfile
- README.md
- docker-compose-dev.yml
fix infinite reload loop due to cache update.
> bugfix: infinite reload loop

- app/app.py
- app/parcellation_api.py
- app/request_utils.py
- app/space_api.py
Properly parses and returns origin data info from https://github.com/FZJ-INM1-BDA/siibra-python/pull/63
Checks attr, so should be backwards compatible.
Also introduces detail flag when encoding region obj to json, this is so that expensive calls (such as getting origin info) are not called unless explicitly set.
> feat: parse and returns origin data info

- .github/workflows/docker-img.yml
- Dockerfile
- docker-compose-dev.yml
- docker-compose-prod.yml
- docker-compose.yml
This PR cleans up in particular `Dockerfile`, where the env var can be explicitly set with `--build-arg PROD_FLAG=1`
> chore: clean up docker files

- .openshift/README.md
This PR adds the admin documentation on the deployment of siibra-api on ebrains infrastructure
> chore: admin documentation

- .github/workflows/github-actions.yml
- Dockerfile
- app/core/parcellation_api.py
- app/service/request_utils.py
- test/core/test_atlas_api.py
- region: labelindex + rgb
- reworked encode parc
- for latest build, use master branch of siibra-config
~~nb: do not merge until~~
- ~~https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/merge_requests/20 and then~~
- ~~https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/merge_requests/18~~
are merged.
comments welcome.
edit: fixes #44
> Fix new siibra-python issues

- .github/workflows/docker-img.yml
- app/core/atlas_api.py
- app/core/parcellation_api.py
- app/core/space_api.py
- app/models/__init__.py
- app/service/request_utils.py
- requirements/dev.txt
first attempt at fixsing #69 
only added links to `atlas` end point. 
If suitable, will add to the rest.
> feat: add links to rest endpoint

- app/core/region_api.py
- test/core/test_regions_api.py
> Feat filter regions

- app/app.py
- test/test_app.py
see #15 
Also some other runtime errors will be handled (not only KG)
> Feat runtimeerror

- app/app.py
feat: reordered matomo logging
bugfix: formalize do not cache list
reordered matomo logging, so that even when cache are hit, the usage is logged.
> fix: caching & middlewares

- app/service/request_utils.py
- test/service/test_request_utils.py
one of the previous commit broke nii patching in siibra-api
this should fix the issue.
I will also provide a test to ensure it does not regress.
> fix unmodified nii file getting saved.

- app/app.py
- app/core/parcellation_api.py
- app/core/region_api.py
- app/core/space_api.py
- mkdocs.yml
bugfix: revert matomo route to log cached responses
bugfix: query of spatial data parcId/region should be optional param
> chore: fix fastapi route descriptive method name

- Dockerfile
- mkdocs.yml
> fix docker build

- app/app.py
- app/core/feature_api.py
- app/core/parcellation_api.py
- app/core/region_api.py
- app/core/siibra_api.py
- app/service/metrics.py
- test/core/test_parcellation_api.py
- test/core/test_siibra_api.py
- New Endpoint to get a feature by id without additional information.
- Added an optional param to filter feature response by type
> Feat feature endpoint

- app/app.py
- app/configuration/diskcache.py
- app/core/region_api.py
- server-conf/gunicorn.conf.py
fix: remove memoization
fix: non-pathed region id param
supercedes #91
> fix: bind address

- app/app.py
- app/core/parcellation_api.py
- app/models/__init__.py
- requirements/common.txt
- test/core/test_parcellation_api.py
first implementation to add pagination to parc features
TODO all end points that return a list should also return paginated result
> add pagination to parc/features

- .github/workflows/docker-img.yml
- Dockerfile
ci/cd: push versioned tags during release
slightly improve the storage efficiency by caching docker build layers
> chore: reorganise dockerfile

- requirements/prod.txt
- added support for region desc
- added support for rgb voi
> bump siibra-python version

- app/__init__.py
- app/configuration/cache_redis.py
- requirements/prod.txt
chore: bumped siibra python version
> chore: add additional redis host port config

- .github/workflows/docker-img.yml
- .github/workflows/github-actions.yml
- .openshift/worker-deploy-template.yml
- api/common/data_handlers/__init__.py
- api/common/data_handlers/compounds/__init__.py
- api/common/data_handlers/compounds/download.py
- api/common/decorators.py
- api/models/_commons.py
- api/server/api.py
- api/server/compounds/__init__.py
- api/server/compounds/download.py
- api/siibra_api_config.py
maint: reworked gha ci/cd
test: add test for server
> feat: download endpoint

- .github/workflows/docker-img.yml
- api/common/data_handlers/compounds/download.py
- api/server/compounds/download.py
> feat: download: add metadata, collapse dir

- api/common/data_handlers/compounds/download.py
- api/serialization/core/region.py
- api/server/features/__init__.py
- api/server/volumes/parcellationmap.py
- api/siibra_api_config.py
- requirements/siibra.txt
feat: added license
maint: update to siibra v0.4a51
maint: no longer require enum in feature type
> feat: download now uses more descriptive filenames

- .github/workflows/docker-img.yml
- api/serialization/features/dataset/ebrains.py
maint: sanity check github ref
> fix: ebrains url ref
